Install apt-get dependences

diff --git a/tools/versions/default/install/install b/tools/versions/default/install/install
--- a/tools/versions/default/install/install
+++ b/tools/versions/default/install/install
@@ -1,25 +1,33 @@
 #!/bin/bash
 
 ###
-#       @author: msune
-#	@organization: i2CAT
-#	@project: Ofelia FP7
+#   @author: roberto monno, msune
+#	@organization: NXW, i2CAT
+#	@project: FIBRE FP7, Ofelia FP7
 #	@description: install module 
 ###
 
 #Inform user
-printHeader "info#" "Using default install module..."
+printHeader "info#" "Using install module..."
 
 ##Main routing
 
 #Install dependencies
-printHeader ">" "Installing dependencies through apt-get(emulating)..."
+printHeader ">" "Installing dependencies through apt-get..."
 
 #Loading dependencies. Note that loadModule will load specific version dependencies file if exists
 loadModule lib/dependencies $NO_RESCUE
-print "/usr/bin/apt-get update" 
-print "/usr/bin/apt-get -y install $DEBIAN_DEPENDENCIES" || error "Could not install dependencies (apt-get)" $NO_RESCUE 
 
+local APTGET=`which apt-get`
+$APTGET clean
+$APTGET autoclean
+$APTGET update
+$APTGET -y install $DEBIAN_DEPENDENCIES || error "Could not install dependencies (apt-get)" $NO_RESCUE
+
+printHeader ">" "Installing dependencies through pip..."
+
+local PIP=`which pip`
+$PIP install $PIP_DEPENDENCIES || error "Could not install dependencies (pip)" $NO_RESCUE
 
 #Calling procedure1 (don't call rollback in case of error)
 loadModule lib/procedure1 $NO_RESCUE
diff --git a/tools/versions/default/install/post-install-hook b/tools/versions/default/install/post-install-hook
--- a/tools/versions/default/install/post-install-hook
+++ b/tools/versions/default/install/post-install-hook
@@ -1,17 +1,20 @@
 #!/bin/bash
 
 ###
-#       @author: msune
-#	@organization: i2CAT
-#	@project: Ofelia FP7
+#   @author: roberto monno, msune
+#	@organization: NXW, i2CAT
+#	@project: FIBRE FP7, Ofelia FP7
 #	@description: post-install module
 ###
 
 #Inform user
-printHeader "info#" "Using default post-install-hook module..."
+printHeader "info#" "Using post-install-hook module..."
 
-#Starting apache
-print "Starting application..."
+#Starting roadm-am
+print "Starting Roadm-AM application..."
+local DEST_DIR=${DESTINATION_DIR:-'../src'}
+local PYTHON=`which python`
+$PYTHON $DEST_DIR/src/main.py || error "Unable to start the main plugin!"
 
 sleep 2
 
